twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # Keenthemes theme layout helper class
        theme: '@App\Service\MetronicThemeHelper'


when@test:
    twig:
        strict_variables: true
